
[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Back", mods = "Command", chars = "\u0015" }, # Delete line
  { key = "Back", mods = "Alt",     chars = "\u001b\u007f" }, # Delete word
]

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/deep_space.toml"
]
